sudo: required
services:
  - docker

before_install:
  - docker build -t diogomesilva/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true diogomesilva/docker-react npm run test
#  - docker run diogomesilva/docker-react npm run test -- --coverage